# Generated by Django 2.2 on 2019-05-15 11:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSet',
            fields=[
                ('dataSet_id', models.AutoField(primary_key=True, serialize=False)),
                ('dataSet_name', models.CharField(max_length=200)),
                ('dataSet_type', models.CharField(max_length=200)),
                ('data_type', models.CharField(default='', max_length=200)),
                ('table_name', models.CharField(max_length=200)),
                ('fields', models.TextField(default='')),
                ('size', models.IntegerField(default=0)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createtime')),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('tree_id', models.AutoField(primary_key=True, serialize=False)),
                ('tree_name', models.CharField(max_length=200)),
                ('tree_type', models.CharField(max_length=200)),
                ('data_type', models.CharField(default='', max_length=200)),
                ('optimize_type', models.CharField(max_length=200, null=True)),
                ('tree_dict', models.TextField(default='')),
                ('fields', models.TextField(default='')),
                ('depth', models.IntegerField(default=0)),
                ('nodes_num', models.IntegerField(default=0)),
                ('datasize', models.IntegerField(default=0)),
                ('costtime', models.FloatField(default=0.0)),
                ('trainacc', models.FloatField(default=0.0)),
                ('sample_ratio', models.FloatField(default='0.3')),
                ('feature_ratio', models.FloatField(default='0.4')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createtime')),
                ('dataSet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainset', to='weixinapi.DataSet')),
                ('outDataSet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outtestset', to='weixinapi.DataSet')),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('analysis_id', models.AutoField(primary_key=True, serialize=False)),
                ('analysis_name', models.CharField(max_length=200)),
                ('accuracy', models.FloatField(default=0.0)),
                ('ifthen', models.TextField(default='')),
                ('content', models.TextField(null=True)),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='createtime')),
                ('dataSet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weixinapi.DataSet')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='weixinapi.Tree')),
            ],
        ),
    ]
